---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  # Secret for database
  - name: awx-prod-postgres-secret
    type: Opaque
    literals:
      - host=awx-postgres
      - port=5432
      - database=awx
      - username=awx
      ##### TO Modify #####
      - password=DatabasePassword
      ##### ~~~~~~~~~~ #####
  # Secret for web interface
  - name: awx-prod-admin-secret
    type: Opaque
    literals:
    ##### To Modify #####
      - password=AdminPassword
    ##### ~~~~~~~~~~ #####

resources:
  - create-pv.yml
  - create-pvc.yml
  - deploy.yml
